language: csharp
mono:
  - latest

solution: PokeD.Core.sln

before_install:
  - git submodule update --init --recursive
  
install:
  - nuget restore PokeD.Core.sln

script:
  - xbuild /p:Configuration=Release PokeD.Core.sln
  - xbuild /p:Configuration=Debug PokeD.Core.sln
  - mono ./packages/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./PokeD.Core.Test/bin/Release/PokeD.Core.Test.dll
 

notifications:
  email:
    on_success: always
