language: csharp

mono: none
dotnet: 2.0
dist: trusty

before_install:
  - git submodule update --init --recursive

script:
 - dotnet restore
 - dotnet build --configuration Release
 - dotnet test ./PokeD.Core.Test/PokeD.Core.Test.csproj
 

notifications:
  email:
    on_success: always
