os: Visual Studio 2017 Preview

configuration:
- Debug
- Release
platform: Any CPU

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  COVERALLS_REPO_TOKEN:  
       secure: CCrbHxhmg6rtTk7kIU5WAEMzZ+tZGSSoVqpdAosFhqN1Fwt1X006XkaVqT4FdKXK

install:
- git submodule update --init --recursive

before_build:
- nuget restore

test_script: 
- choco install codecov
- cd PokeD.Core.Test
- dotnet tool install -g coveralls.net
- dotnet add package coverlet.msbuild
- dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude=[NUnit*]*
- csmacnz.coveralls --opencover coverage.opencover.xml -r %COVERALLS_REPO_TOKEN%
- codecov -f "coverage.opencover.xml"
- cmd: .\tools\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage_netfx.xml -r %COVERALLS_REPO_TOKEN%
- cd ..

build:
  project: PokeD.Core.sln
  verbosity: minimal
